# Generated by Django 2.1.3 on 2018-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_to_send', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
    ]
