# Generated by Django 2.1.3 on 2018-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='file_to_send',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
